#spring:
#  datasource:
#    #配置hikari连接池
#    hikari:
#      minimum-idle: 4
#      maximum-pool-size: 16
#      connection-timeout: 10000
#      idle-timeout: 30000
#      connection-init-sql: set names utf8mb4
#    #动态数据源配置
#    dynamic:
#      #主数据源
#      primary: dmsscloud
#      datasource:
#        #数据源a01
#        dmsscloud:
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://18.139.18.90:3306/dmsscloud?useUnicode=true&characterEncoding=utf8&usePipelineAuth=false&allowMultiQueries=true&useSSL=false
#          username: root
#          password: mysql
#        #数据源a02
#        dmsscloudtest:
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://18.139.18.90:3306/dmsscloud?useUnicode=true&characterEncoding=utf8&usePipelineAuth=false&allowMultiQueries=true&useSSL=false
#          username: root
#          password: mysql
#数据源a03
#        a03:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/a03?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#          username: root
#          password: 123456
qintaozhi: 111,222,333

#async:
#  executor:
#    thread:
#      core_pool_size: 10
#      max_pool_size : 50
#      queue_capacity : 1000
#      keep_alive_seconds : 300

url:
  orderUrl: 1231
  userUrl: 313
  shoppingUrl: 113

corepoolsize: 10
maxpoolsize: 50
queuecapacity: 1000
keepaliveseconds: 300

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/dmsscloud?useUnicode=true&characterEncoding=utf8&usePipelineAuth=false&allowMultiQueries=true&useSSL=false
#    username: root
#    password: qintaozhi
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: demo-service

spring:
  datasource:
    url: jdbc:mysql://18.139.18.90:3306/dmsscloud?useUnicode=true&characterEncoding=utf8&usePipelineAuth=false&allowMultiQueries=true&useSSL=false
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: demo-service
  rabbitmq:
    addresses: 18.139.18.90:5672
    username: retailcloud
    password: retailcloud
    connection-timeout: 0
  redis:
    host: 18.139.18.90
    port: 6379
    lettuce:
      pool:
        max-active: 100
        #连接池中最大空闲连接
        max-idle: 10
        #连接池中最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值代表没有限制）
        max-wait: -1
    timeout: 5000
    database: 0
    password: SXa^ExJIqtHddcX6




#mybatis
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*.xml


#eureka
server:
  port: 18888
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.254.22:7001/eureka/
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间

feign:
  hystrix:
    enabled: true























